### ISSUE TITLE
API call limit

### ISSUE THREAD

**Issue by tczee36** [the-javapocalypse/Twitter-Sentiment-Analysis#1]
How to avoid the following error?

Traceback (most recent call last):
  File "tweet.py", line 30, in <module>
    for tweet in tweets:
  File "/usr/local/lib/python3.7/dist-packages/tweepy/cursor.py", line 49, in __next__
    return self.next()
  File "/usr/local/lib/python3.7/dist-packages/tweepy/cursor.py", line 197, in next
    self.current_page = self.page_iterator.next()
  File "/usr/local/lib/python3.7/dist-packages/tweepy/cursor.py", line 108, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kargs)
  File "/usr/local/lib/python3.7/dist-packages/tweepy/binder.py", line 250, in _call
    return method.execute()
  File "/usr/local/lib/python3.7/dist-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Twitter error response: status code = 429

thanks

**Comment by rohanvivek** [comment]
Add wait_on_rate_limit=True on the API call like this:

```api = tweepy.API(auth, wait_on_rate_limit=True)```
This will make the rest of the code obey the rate limit
